apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: keycloak-lab
type: Opaque
stringData:
  # Cambiá estas credenciales antes de aplicar en un entorno compartido
  POSTGRESQL_USER: keycloak
  POSTGRESQL_PASSWORD: keycloak-lab-pass
  POSTGRESQL_DATABASE: keycloak
  POSTGRESQL_ADMIN_PASSWORD: keycloak-admin-pass
